services:
  - type: web
    name: studysphere-backend
    env: python
    buildCommand: pip install -r backend/requirement.txt
    startCommand: python backend/app.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
